version: 2

sources:
  - name: raw
    database: demo_db        
    schema: demo_schema      
    tables:
      - name: raw_sales 
        description: "Raw sales data from source system"
        loaded_at_field: updated_at
        config:
          freshness:
            warn_after: { count: 12, period: hour }
            error_after: { count: 24, period: hour }