version: 2

sources:
  - name: raw
    database: demo_db
    schema: demo_schema
    tables:
      - name: raw_sales
        freshness:
          warn_after: { count: 12, period: hour }
          error_after: { count: 24, period: hour }
        loaded_at_field: updated_at